name: Testes com Mocha

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



 jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Node.js   
        uses: actions/setup-node@v3
        with: 
          node-version: '16'
      - name: Instalar dependencias
        run: npm install

      - name: Garantir permissões de execução para Mocha
        run: chmod +x ./node_modules/.bin/mocha

      - name: Verificar o caminho do Mocha
        run: ls -l 
